baseURL = 'https://prasanthabr.github.io/0din'
languageCode = 'en-us'
title = '0din'
theme = "smol"

# Parameters
[params]
    subtitle = "Writing and learnings for my future self"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/prasanthabr"
        weight = 1 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://toot.io/@pa"
        weight = 2

    [[menu.footer]]
        name = "about"
        url = "/about/"
        weight = 3